[package]
name = "esi_example_app"
version = "0.2.0"
authors = ["Kailan Blanks <kailan@enviark.com>"]
edition = "2018"
publish = false

[dependencies]
fastly = "^0.8"
esi = { path = "../esi" }
log = "^0.4"
env_logger = "^0.9"